Ext.define('App.view.person.ShowDetails', {
    extend: 'Ext.Panel',
    xtype: 'personshowdetails',

    cls: 'person-details',
    title: 'Details',

    bind: {
        record: '{record}'
    },

    tpl: [
        '<div class="block-section">',
            '<div class="item">',
                '<div class="label">Usuario</div>',
                '<div class="value">{username}</div>',
            '</div>',
            '<tpl if="phone">',
                '<div class="item">',
                    '<div class="label">Telefono</div>',
                    '<div class="value">{phone}</div>',
                '</div>',
            '</tpl>',
            '<tpl if="extension">',
                '<div class="item">',
                    '<div class="label">Extenciones</div>',
                    '<div class="value">{extension}</div>',
                '</div>',
            '</tpl>',
        '</div>',
        '<div class="block-section">',
            '<div class="item">',
                '<div class="label">Email</div>',
                '<div class="value">{email}</div>',
            '</div>',
            '<tpl if="skype">',
                '<div class="item">',
                    '<div class="label">Skype</div>',
                    '<div class="value">{skype}</div>',
                '</div>',
            '</tpl>',
            '<tpl if="linkedin">',
                '<div class="item">',
                    '<div class="label">LinkedIn</div>',
                    '<div class="value">{linkedin}</div>',
                '</div>',
            '</tpl>',
        '</div>',
        '<div class="block-section">',
            '<div class="item">',
                '<div class="label">Birthday</div>',
                '<div class="value">{birthday:date("F jS, Y")}</div>',
                '<div class="extra">{birthday:dateDiff(new Date())}</div>',
            '</div>',
            '<div class="item">',
                '<div class="label">Fecha de entrada</div>',
                '<div class="value">{started:date("F jS, Y")}</div>',
                '<tpl if="!ended">',
                    '<div class="extra">{started:dateDiff(new Date())}</div>',
                '</tpl>',
            '</div>',
            '<tpl if="ended">',
                '<div class="item">',
                    '<div class="label">Fecha de salida</div>',
                    '<div class="value">{ended:date("F jS, Y")}</div>',
                    '<div class="extra">{started:dateDiff(values.ended)}</div>',
                '</div>',
            '</tpl>',
        '</div>'
    ]
});
